name:                audit
version:             0.1.0.0
github:              "khuldraeseth/audit"
license:             BSD3
author:              "Khuldraeseth"
maintainer:          "khuldraeseth@gmail.com"
copyright:           "2021 Khuldraeseth"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/khuldraeseth/audit#readme>

dependencies:
- base >= 4.7 && < 5
- http-conduit
- bytestring
- html-conduit
- conduit
- xml-conduit
- http-client
- resourcet
- text
- containers
- parsec

library:
  source-dirs: src

executables:
  audit-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - audit

tests:
  test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - audit
